"""test

Revision ID: 56e59466c7d4
Revises: 
Create Date: 2024-10-06 14:59:41.602740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e59466c7d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('ad_group',
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('ad_group_id')
    )
    op.create_table('ad_group_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_group.ad_group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_group_stats')
    op.drop_table('ad_group')
    op.drop_table('campaign')
    # ### end Alembic commands ###
